name: kueens
description: A new Flutter application for women's.

version: 4.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_auth: any
  firebase_core: any
  cloud_firestore: any
  firebase_analytics: ^6.3.0
  bottom_navy_bar: ^5.6.0
  image_picker: any
  uuid: 2.2.2
  firebase_storage: 4.0.0
  multi_image_picker: any
  flutter_absolute_path: any
  location: 3.0.2
  http: 0.12.2
  html: 0.14.0+3
  rxdart: ^0.24.1
  shared_preferences: ^0.5.12+4
  geocoder: ^0.2.1
  video_trimmer: ^0.3.2
  video_thumbnail: ^0.2.4
  cached_network_image: any
  carousel_slider: ^2.2.1
  smooth_star_rating: ^1.1.1
  flutter_staggered_animations: ^0.1.2
  mvc_pattern: ^3.4.1
  firebase_messaging: any
  photo_view: ^0.10.2
  flutter_settings_screens: ^0.2.1
  google_maps_flutter: 1.0.3
  smart_select: ^4.3.2
  firebase_dynamic_links: any
  flutter_share: ^1.0.3
  intl: ^0.16.1
  restcountries: ^0.0.3
  intl_phone_field: ^1.4.2
  flutter_image_compress: ^0.7.0
  numberpicker: ^1.3.0
  purchases_flutter: ^2.0.3
  flutter_svg: ^0.19.3
  assets_audio_player: any
  flutter_countdown_timer: ^3.0.0
  flutter_local_notifications: any
  feature_discovery: any
  paginate_firestore: any
  url_launcher: any


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/audio/

  fonts:
    - family: Varela
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
